USE OlimpiadasDB_Anio;
GO

-- 1. Validar conteo exacto de todas las tablas tras la restauración
SELECT CAST('PAIS' AS VARCHAR(20)) AS Tabla, COUNT(*) AS TotalRegistros FROM PAIS
UNION ALL SELECT 'POBLACION_PAIS', COUNT(*) FROM POBLACION_PAIS
UNION ALL SELECT 'SEDE', COUNT(*) FROM SEDE
UNION ALL SELECT 'EDICION_JUEGOS', COUNT(*) FROM EDICION_JUEGOS
UNION ALL SELECT 'DEPORTE', COUNT(*) FROM DEPORTE
UNION ALL SELECT 'EVENTO', COUNT(*) FROM EVENTO
UNION ALL SELECT 'FUENTE_DATOS', COUNT(*) FROM FUENTE_DATOS
UNION ALL SELECT 'ATLETA', COUNT(*) FROM ATLETA
UNION ALL SELECT 'PARTICIPACION', COUNT(*) FROM PARTICIPACION;

-- 2. Validar últimas ediciones presentes y muestra de PARTICIPACION (SELECT *)
SELECT TOP 5 id_edicion, anio, CAST(temporada AS VARCHAR(15)) AS temporada, id_sede 
FROM EDICION_JUEGOS ORDER BY anio DESC;

SELECT TOP 5 id_participacion, id_atleta, id_edicion, id_evento, id_pais_representado, CAST(ISNULL(medalla, 'NULL') AS VARCHAR(10)) AS medalla 
FROM PARTICIPACION ORDER BY id_participacion DESC;
GO