USE OlimpiadasDB_Deporte;
GO

SELECT CAST('PAIS' AS VARCHAR(20)) AS Tabla, COUNT(*) AS TotalRegistros FROM PAIS
UNION ALL SELECT 'POBLACION_PAIS', COUNT(*) FROM POBLACION_PAIS
UNION ALL SELECT 'SEDE', COUNT(*) FROM SEDE
UNION ALL SELECT 'EDICION_JUEGOS', COUNT(*) FROM EDICION_JUEGOS
UNION ALL SELECT 'DEPORTE', COUNT(*) FROM DEPORTE
UNION ALL SELECT 'EVENTO', COUNT(*) FROM EVENTO
UNION ALL SELECT 'FUENTE_DATOS', COUNT(*) FROM FUENTE_DATOS
UNION ALL SELECT 'ATLETA', COUNT(*) FROM ATLETA
UNION ALL SELECT 'PARTICIPACION', COUNT(*) FROM PARTICIPACION;

SELECT EJ.anio, COUNT(*) AS Participaciones_Athletics
FROM PARTICIPACION PAR
INNER JOIN EDICION_JUEGOS EJ ON EJ.id_edicion = PAR.id_edicion
INNER JOIN EVENTO EV ON EV.id_evento = PAR.id_evento
INNER JOIN DEPORTE D ON D.id_deporte = EV.id_deporte
WHERE D.nombre = 'Athletics' AND EJ.anio IN (2012, 2016, 2020, 2024)
GROUP BY EJ.anio ORDER BY EJ.anio DESC;

SELECT TOP 5 id_participacion, id_atleta, id_edicion, id_evento, id_pais_representado, CAST(ISNULL(medalla, 'NULL') AS VARCHAR(10)) AS medalla 
FROM PARTICIPACION ORDER BY id_participacion DESC;
GO